### ISSUE TITLE
Not working, Waiting for your Location...

### ISSUE THREAD

**Issue by moosalim** [iamriajul/adhan-dart#6] opened 2021-01-10 16:58 UTC
Assalam Alaykom Brother

Thank you very much for the plugin........ Jazak Allah Khair

I just tried the plugin in the iphone simulator and also in my iphone devise but it does not work. I get this message on screen: "Waiting for your Location..."

I have waited for long time without any result. Can you pleas check.

I have used the example code you placed in GitHub :

```
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final location = new Location();
  String locationError;
  PrayerTimes prayerTimes;

  @override
  void initState() {
    getLocationData().then((locationData) {
      if (mounted) {
        return;
      }
      if (locationData != null) {
        setState(() {
          prayerTimes = PrayerTimes(Coordinates(locationData.latitude, locationData.longitude),
              DateComponents.from(DateTime.now()), CalculationMethod.karachi.getParameters());
        });
      } else {
        setState(() {
          locationError = "Couldn't Get Your Location!";
        });
      }
    });

    super.initState();
  }

  Future<LocationData> getLocationData() async {
    var _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return null;
      }
    }

    var _permissionGranted = await location.hasPermission();
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission();
      if (_permissionGranted != PermissionStatus.granted) {
        return null;
      }
    }

    return await location.getLocation();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Builder(
              builder: (BuildContext context) {
                if (prayerTimes != null) {
                  return Column(
                    children: [
                      Text(
                        'Prayer Times for Today',
                        textAlign: TextAlign.center,
                      ),
                      Text('Fajr Time: ' + DateFormat.jm().format(prayerTimes.fajr)),
                      Text('Sunrise Time: ' + DateFormat.jm().format(prayerTimes.sunrise)),
                      Text('Dhuhr Time: ' + DateFormat.jm().format(prayerTimes.dhuhr)),
                      Text('Asr Time: ' + DateFormat.jm().format(prayerTimes.asr)),
                      Text('Maghrib Time: ' + DateFormat.jm().format(prayerTimes.maghrib)),
                      Text('Isha Time: ' + DateFormat.jm().format(prayerTimes.isha)),
                    ],
                  );
                }
                if (locationError != null) {
                  return Text(locationError);
                }
                return Text('Waiting for Your Location...');
              },
            )
          ],
        ),
      ),
    );
  }
}
```

**Comment by iamriajul** [comment] 2021-01-11 02:58
Your Phone's GPS/Location service may be slow or turned off, and it has nothing to do with the actual library itself.

-- https://github.com/iamriajul/adhan-dart/issues/2#issuecomment-700518681_

**Comment by iamriajul** [comment] 2021-01-11 03:00
Duplicate of #2

**Comment by iamriajul** [comment] 2021-01-11 03:05
@moosalim Waalaikumussalam brother.

I haven't tested the example code (that you used) on an iOS device/simulator.
please find your own way to find GPS coordinates. 

Thanks.

**Comment by moosalim** [comment] 2021-01-11 03:06
My phone/gps is working fine, not slow.

The issue seems to be in the example code provided by you. 

If I remove this it works:

if (mounted) {
        return;
      }

Please try it

**Comment by iamriajul** [comment] 2021-01-11 03:13
`if (mounted) {
return;
}`
#1 this was the reason behind mounted checking.

**Comment by moosalim** [comment] 2021-01-11 03:17
Yes, this is the reason.

Please test the example code.

Please note that the example code is provided by you. It is not my code

**Comment by iamriajul** [comment] 2021-01-11 03:19
Yes, this was my typing mistake, this should have been `if (!mounted) { return; }`.
please check now, I have just pushed changes to the example code.
![image](https://user-images.githubusercontent.com/24244379/104144602-09670380-53ee-11eb-88ba-9d01834dfc2c.png)

**Comment by iamriajul** [comment] 2021-01-11 03:21
@moosalim can you please check if this is working or not?

**Comment by moosalim** [comment] 2021-01-11 17:45
It works fine if I use this: 

`if (mounted) { return; }`

**Comment by moosalim** [comment] 2021-01-11 17:48
Can you please add all the library features and options to the example. some of them are not clear.

also I noticed that you have one file in the library for Qibla. can you please implement that in the example.

**Closed** 2021-01-12 05:51 UTC
Labels: bug
