### ISSUE TITLE
Even with offset value some location have one hour difference like new york

### ISSUE THREAD

**Issue by HamadBangash353** [iamriajul/adhan-dart#23] opened 2021-04-12 06:47 UTC
```
 tz.initializeTimeZones();
        String timeZoneName = tzmap.latLngToTimezoneString(lat, lng);
        var timeZoneLocation = tz.getLocation(timeZoneName);
        final tz.TZDateTime now = tz.TZDateTime.now(timeZoneLocation);
        var timeInUtc = DateTime.utc(1970, 1, 1);
        var timeZone =
            timeZoneLocation.timeZone(timeInUtc.millisecondsSinceEpoch);
        print(timeZone.offset);

        currentLocation = cityName;
        setState(() {
          final methodParams = selectedMethod != null
              ? selectedMethod.getParameters()
              : adhan.CalculationMethod.tehran.getParameters();
          methodParams.madhab =
              selectedMazhab != null ? selectedMazhab : adhan.Madhab.hanafi;
          methodParams.highLatitudeRule = selectedLatitude != null
              ? selectedLatitude
              : adhan.HighLatitudeRule.middle_of_the_night;
          prayerTimes = adhan.PrayerTimes(adhan.Coordinates(lat, lng),
              adhan.DateComponents.from(now), methodParams,
              utcOffset: Duration(milliseconds: timeZone.offset));
```

**This is how i calculate prayer times but in new york it has one hour deff, and for newyork offset value is -18000000 in millis.**

**Comment by iamriajul** [comment] 2021-04-17 03:52
You don't need to pass utcOffset if your device (in your case android) is already running in your desired timezone.

**Comment by iamriajul** [comment] 2021-04-17 10:56
might be duplicate of #25

**Closed by iamriajul** 2021-04-17 10:56 UTC
Labels: question
